SELECT
   ELEVATION,
   GEO_LAT,
   GEO_LONG,
   TIME_ZONE,
   TIMESTAMP,
   T1_IDX,
   T1_ID_LOC,
   T1_TIMESTAMP_UNIX,
   PRESSURE_MSL,
   TEMPERATURE_2M,
   TEMPERATURE_80M,
   WINDGUSTS_10M,
   WINDSPEED_10M,
   WINDSPEED_80M,
   WINDDIRECTION_10M,
   WINDDIRECTION_80M,
   TIME,
   TIMESTAMP_DAY
FROM (
  SELECT
    *,
    ROW_NUMBER() OVER (PARTITION BY T1_ID_LOC, TIMESTAMP_DAY, TIME ORDER BY TIMESTAMP DESC) AS q01
  FROM (
    SELECT *, date(TIMESTAMP) AS TIMESTAMP_DAY
    FROM {{ ref('stg_step1') }}
  )
)
WHERE (q01 = 1)