SELECT
  *,
  AVG(sq_er_PRESSURE_MSL) OVER (PARTITION BY ID_LOC, TIME) AS msq_er_PRESSURE_MSL,
  AVG(sq_er_TEMPERATURE_2M) OVER (PARTITION BY ID_LOC, TIME) AS msq_er_TEMPERATURE_2M,
  AVG(sq_er_TEMPERATURE_80M) OVER (PARTITION BY ID_LOC, TIME) AS msq_er_TEMPERATURE_80M,
  AVG(sq_er_WINDGUSTS_10M) OVER (PARTITION BY ID_LOC, TIME) AS msq_er_WINDGUSTS_10M,
  AVG(sq_er_WINDSPEED_10M) OVER (PARTITION BY ID_LOC, TIME) AS msq_er_WINDSPEED_10M,
  AVG(sq_er_WINDSPEED_80M) OVER (PARTITION BY ID_LOC, TIME) AS msq_er_WINDSPEED_80M
FROM (
  SELECT
    *,
    POWER((PRESSURE_MSL_PRED - PRESSURE_MSL_PAST), 2.0) AS sq_er_PRESSURE_MSL,
    POWER((TEMPERATURE_2M_PRED - TEMPERATURE_2M_PAST), 2.0) AS sq_er_TEMPERATURE_2M,
    POWER((TEMPERATURE_80M_PRED - TEMPERATURE_80M_PAST), 2.0) AS sq_er_TEMPERATURE_80M,
    POWER((WINDGUSTS_10M_PRED - WINDGUSTS_10M_PAST), 2.0) AS sq_er_WINDGUSTS_10M,
    POWER((WINDSPEED_10M_PRED - WINDSPEED_10M_PAST), 2.0) AS sq_er_WINDSPEED_10M,
    POWER((WINDSPEED_80M_PRED - WINDSPEED_80M_PAST), 2.0) AS sq_er_WINDSPEED_80M
  FROM {{ ref('stg_step2bcd') }}
)